# Generated by Django 6.0.4 on 2026-04-23 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("game_id", models.IntegerField(primary_key=True, serialize=False)),
                ("game_date", models.DateTimeField()),
                ("completed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("team_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("abbreviation", models.CharField(max_length=5)),
                ("logo_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="GamePrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("utah_win_pct", models.FloatField()),
                ("predicted_home_score", models.IntegerField(null=True)),
                ("predicted_away_score", models.IntegerField(null=True)),
                ("utah_won", models.BooleanField(null=True)),
                ("prediction_correct", models.BooleanField(null=True)),
                ("cached_data", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prediction",
                        to="predictor.game",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="away_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="away_games",
                to="predictor.team",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="home_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_games",
                to="predictor.team",
            ),
        ),
    ]
